name: Hello World Demo Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  first-jobtest:
    runs-on: ubuntu-latest

    steps:
      - name: greetings
        run: echo "Hello, World!"
        